### ISSUE TITLE
Auth concept for Cases

### ISSUE THREAD

**Issue by smarthomeagentur** [wirewirewirewire/pandoa-backend#6]
We need a concept for authentication for submittend Cases. The User should be able to edit own cases. Also there should be some workflow to enable/activate cases after verification

**Comment by Kaipirinha** [comment]
I would use something existing, universal and commonly used like google/facebook oauth/oidc:

![image](https://user-images.githubusercontent.com/18609304/77224593-98591580-6b67-11ea-84ef-3a728c9a577d.png)

But that would involve the frontend as well as the backend, e.g.:

Phone -> App (Authenticates) -sendsBearerToken-> Backend (Retrieves User Data with bearer token and stores/retriev it accordingly)

**Comment by smarthomeagentur** [comment]
auth via passport linked to case is implemented
